const express = require('express');
const route = express.Router();
const assignment = require("./assigment");
const session = require("./session");
const course = require("./course");
const teacher = require("./teacher");
const controller = require("../controller/authentication");

route.get('/teacher/logined',controller.authenticate,teacher.logined);
route.post('/teacher/view/course',controller.authenticate,course.detail);
route.post('/teacher/view/studentsInACourse',controller.authenticate,course.studentsInACourse);
route.post('/teacher/search/studentsInACourse',controller.authenticate,course.searchStudentsInACourse);
route.post('/teacher/view/searchStudentsInACourse',controller.authenticate,course.groupStudentsInACourse);
route.post('/teacher/create/assignment',controller.authenticate,assignment.create);
route.post('/teacher/score/assignment',controller.authenticate,assignment.score);
route.post('/teacher/update/assignment',controller.authenticate,assignment.updateAssignment);
route.post('/teacher/delete/assignment',controller.authenticate,assignment._delete);
route.post('/teacher/view/assignments',controller.authenticate,assignment.view);
route.post('/teacher/viewDetail/assignment',controller.authenticate,assignment.viewDetail);
route.post('/teacher/viewByGroup/assignments',controller.authenticate,assignment.viewByGroup);
route.post('/teacher/delay/assignment',controller.authenticate,assignment.delay);
route.get('/teacher/delay/assignment/:assignment_id',controller.authenticate,assignment.delayList);
route.get('/teacher/detail/session',controller.authenticate,session.detail);
route.post('/teacher/create/session',controller.authenticate,session.create);
route.get('/teacher/detail/assignment',controller.authenticate,assignment.detail);
route.get('/teacher/viewAll/assignment',controller.authenticate,assignment.viewAll);
route.post('/teacher/viewAll/session',controller.authenticate,session.displayAll);
route.post('/teacher/viewByGroup/session',controller.authenticate,session.displayByGroup);
route.post('/teacher/record/attendance',controller.authenticate,session.attendance);
route.post('/teacher/view/attendance',controller.authenticate,session.studentInSession);
route.post('/teacher/viewByGroup/attendance',controller.authenticate,session.groupAttendance);
route.post('/teacher/search/attendance',controller.authenticate,session.searchAttendance);
route.get('/teacher/getStudent/assignment/:id',controller.authenticate,assignment.getStudent);
route.get('/teacher/return/assignment/:id',controller.authenticate,assignment.returnStudent);
route.post('/teacher/upload/material',controller.authenticate,course.UploadMaterial);
route.post('/teacher/return/assignment/student',controller.authenticate,assignment.returnAssignmentStudent);
route.get('/teacher/displayAll/material/:course_id',controller.authenticate, course.ListMaterial);
route.post('/teacher/displayOne/material',controller.authenticate, course.ListOneMaterial);
route.post('/teacher/update/material',controller.authenticate, course.UpdateMaterial);
route.post('/teacher/delete/material',controller.authenticate, course.deleteMaterial);

module.exports = route;